### PR TITLE
Support for scala 2.10

### LINKED ISSUE #76: Support for scala 2.10
Support for scala 2.10

### PR DESCRIPTION
**Pull request by phearnot**
This hopefully fixes #76.

I've bumped lib versions, replaced legacy scala plugin with the more recent scala-maven-plugin and migrated tests to scalatest.

### CODE REVIEW

**Comment by slorber** [comment]
Hope this will be integrated soon!

**Comment by tiagoboldt** [comment]
I wonder if this project has died and should be forked to carry on..

**Comment by slorber** [comment]
Yes it seems it has died and now you can use:
https://github.com/FasterXML/jackson-module-scala

**Comment by jcranky** [comment]
I'm also taking a look at the Zeebox fork: https://github.com/zeebox/jerkson/ - seems to have been ported to 2.10, didn't test it yet, though.

Now, this [ABANDONED] flag in the project description bothers me a whole lot. At least there seems to have a ton of forks, just don't know which one to trust =(

**Comment by jcranky** [comment]
And another good-looking option: https://github.com/wg/jacks - which I also didn't test yet :P

**Comment by tiagoboldt** [comment]
As this is now a list of alternatives, I'm trying http://argonaut.io/

**Comment by slorber** [comment]
Argonaut seems nice and has Tony Morris (Scalaz) as developer so I guess we can expect some quality.

I use this one:
https://github.com/FasterXML/jackson-module-scala
It has a good support from the author and works fine in production for my case.

**Pull request closed without merging**
