### PR TITLE
CaseClassSerializer should also ignore 'transient' fields.

### PR DESCRIPTION
**Pull request by aryairani**
Hi Coda,

At https://github.com/codahale/jerkson/blob/development/src/main/scala/com/codahale/jerkson/ser/CaseClassSerializer.scala, I saw it was possible to ignore fields by adding the `@JsonIgnore` annotation.    This is fine as long as I don't extend any classes I can't edit.  

Please consider this patch which modifies CaseClassSerializer to also ignore fields which have the `@scala.transient` annotation.  Many libraries existing use this standard annotation on their datastructures (and I inherit from them, so I'm getting stray fields in my JSON). Thanks!

### CODE REVIEW

**Comment by codahale** [comment]
Add a test for this and I'm sold.

**Comment by aryairani** [comment]
Will do.

-Arya

**Comment by aryairani** [comment]
How embarrassing :-\  The first commit wouldn't even compile.  This one's better.  (I'm new.)

**Comment by codahale** [comment]
Thanks!

**Comment by adamkaplan** [comment]
I'm curious as to why the case class deserializer doesn't seem to ignores neither transient nor JsonIgnore. Is there a good reason for this? From what I can tell, it means Jerkson can't eat what it produces.

**Comment by codahale** [comment]
Mostly because I don't use `@transient` or `@JsonIgnore` and have relied on the kindness of strangers for consistency supporting them. Feel free to submit a patch adding that functionality to `CaseClassDeserializer`.

**Comment by aryairani** [comment]
Yeah, I only patched CaseClassSerializer, because I don't do any deserialization in jersey.

**Comment by adamkaplan** [comment]
Cool. I might patch it, but our production systems are currently locked into Scala 2.8.1, which you aren't supporting anymore.

**Comment by codahale** [comment]
Not won't -- can't.

Modern versions of Jackson can't handle the invalid bytecode that 2.8.1 generates for generic signatures.

**Pull request merged**
